chore: :hammer: Added back testing to pre-commit file, becaue I found what was causing the problems

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -12,6 +12,14 @@ else
   COMMIT_MSG=""
 fi
 
+# Check if test files exist
+TEST_FILES=$(find ../src -name '*.test.js' -o -name '*.spec.js' | wc -l)
+
+if [ "$TEST_FILES" -gt 0 ]; then
+  # Exit if tests fail
+  npm run test || exit 1
+fi
+
 # Format JavaScript code
 npm run format
 
